FROM python:3.12.10-slim

# Set work directory
WORKDIR /app

# Install dependencies

ADD api-constantec/requirements_dev.txt ./

RUN pip install --no-cache-dir -r requirements_dev.txt

# Copy entrypoint script or start from command line (code will come from volume)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]