FROM python:3.12.10-slim

# Directorio de trabajo
WORKDIR /app

# Intalar dependecias del sistema para PostgreSQL
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar dependencias de python
COPY api-constantec/requirements_dev.txt ./
RUN pip install --no-cache-dir -r requirements_dev.txt

# Copiar todo el contenido de la carpeta local al contenedor
COPY api-constantec/ .

# Comando de ejecución para FastAPI
# --proxy-headers --trusted-hosts "*"
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]